import "server-only";
import type Stripe from "stripe";
import { prisma } from "@/lib/prisma";
import { fireAutomationTrigger } from "@/lib/automations";
import { getStripeClient } from "@/lib/stripe";

async function findOrCreateContactForStripeCustomer({
  customerId,
  email,
  name,
}: {
  customerId: string;
  email: string | null;
  name: string | null;
}) {
  const linked = await prisma.contact.findUnique({ where: { stripeCustomerId: customerId } });
  if (linked) return linked;

  if (email) {
    // Contact.email isn't unique, so if duplicates ever exist, pick the
    // same one every time (oldest first) instead of whatever order
    // Postgres happens to return — an arbitrary pick here could attach a
    // client's payment to the wrong contact record on a later webhook.
    const byEmail = await prisma.contact.findFirst({
      where: { email },
      orderBy: { createdAt: "asc" },
    });
    if (byEmail) {
      return prisma.contact.update({
        where: { id: byEmail.id },
        data: { stripeCustomerId: customerId },
      });
    }
  }

  const parts = (name || email || "Stripe Customer").trim().split(" ");
  const firstName = parts[0] || "Stripe";
  const lastName = parts.slice(1).join(" ") || "Customer";

  return prisma.contact.create({
    data: {
      firstName,
      lastName,
      email: email || null,
      status: "CLIENT", // if they're paying, they're a client
      stripeCustomerId: customerId,
    },
  });
}

function contactDisplayName(c: { firstName: string; lastName: string; businessName: string | null }) {
  return c.businessName || `${c.firstName} ${c.lastName}`;
}

// Stripe API versions differ in where the generating subscription lives on
// an Invoice — modern versions nest it under `parent.subscription_details`,
// older ones (and some webhook payloads, depending on the account's pinned
// version) expose a top-level `subscription` field. Since this integration
// doesn't pin an API version (see getStripeClient), check both so
// isRecurring classification doesn't silently fail on either shape.
function invoiceSubscriptionId(stripeInvoice: Stripe.Invoice): string | null {
  const nested = stripeInvoice.parent?.subscription_details?.subscription;
  if (nested) return typeof nested === "string" ? nested : nested.id;
  const legacy = (stripeInvoice as unknown as { subscription?: string | { id: string } | null })
    .subscription;
  if (legacy) return typeof legacy === "string" ? legacy : legacy.id;
  return null;
}

// Handles both `invoice.finalized` (an invoice is ready to be paid — mirrors
// the CRM's own "Sent" status) and `invoice.paid`. Upserts by stripeInvoiceId
// so replayed/duplicate webhook deliveries update the same row instead of
// creating a second one.
export async function syncStripeInvoice(stripeInvoice: Stripe.Invoice, status: "SENT" | "PAID") {
  const customerId =
    typeof stripeInvoice.customer === "string"
      ? stripeInvoice.customer
      : stripeInvoice.customer?.id;
  if (!customerId) return;

  const contact = await findOrCreateContactForStripeCustomer({
    customerId,
    email: stripeInvoice.customer_email ?? null,
    name: stripeInvoice.customer_name ?? null,
  });

  if (status === "PAID" && contact.status === "LEAD") {
    await prisma.contact.update({ where: { id: contact.id }, data: { status: "CLIENT" } });
  }

  const amount = (status === "PAID" ? stripeInvoice.amount_paid : stripeInvoice.amount_due) / 100;
  const description =
    stripeInvoice.description || stripeInvoice.lines.data[0]?.description || "Stripe invoice";
  const dueDate = stripeInvoice.due_date ? new Date(stripeInvoice.due_date * 1000) : null;
  const paidAtSeconds = stripeInvoice.status_transitions?.paid_at;
  const paidAt = status === "PAID" ? new Date((paidAtSeconds ?? Math.floor(Date.now() / 1000)) * 1000) : null;
  // Drives "recurring revenue collected" vs "one-time revenue collected" —
  // an invoice generated by a subscription is recurring, everything else
  // (one-off Stripe invoices, manually-entered invoices) is one-time.
  const isRecurring = invoiceSubscriptionId(stripeInvoice) !== null;

  await prisma.invoice.upsert({
    where: { stripeInvoiceId: stripeInvoice.id },
    update: {
      description,
      amount,
      status,
      dueDate,
      paidAt,
      isRecurring,
    },
    create: {
      stripeInvoiceId: stripeInvoice.id,
      contactId: contact.id,
      description,
      amount,
      status,
      issuedDate: new Date(stripeInvoice.created * 1000),
      dueDate,
      paidAt,
      isRecurring,
    },
  });

  if (status === "PAID") {
    await fireAutomationTrigger("INVOICE_PAID", {
      contactId: contact.id,
      summary: `${contactDisplayName(contact)} — ${description} ($${amount})`,
    });
  }
}

// Stripe's modern refund path for a paid invoice is a Credit Note (the
// Charge object no longer carries a direct `invoice` link in this API
// version). Rather than summing individual credit notes ourselves — and
// risking double-counting on a replayed webhook — we re-fetch the invoice
// from Stripe and read its `post_payment_credit_notes_amount`, which is
// Stripe's own running total of everything credited back after payment.
// That makes this handler naturally idempotent no matter how many times
// `credit_note.created`/`credit_note.updated` gets redelivered.
export async function syncStripeRefund(creditNote: Stripe.CreditNote) {
  const invoiceId = typeof creditNote.invoice === "string" ? creditNote.invoice : creditNote.invoice?.id;
  if (!invoiceId) return;

  const invoice = await prisma.invoice.findUnique({ where: { stripeInvoiceId: invoiceId } });
  if (!invoice) return; // not an invoice we're tracking — nothing to net out

  const stripeInvoice = await getStripeClient().invoices.retrieve(invoiceId);
  const refundedAmount = stripeInvoice.post_payment_credit_notes_amount / 100;
  if (refundedAmount <= 0) return;

  await prisma.invoice.update({
    where: { id: invoice.id },
    data: { refundedAmount, refundedAt: new Date() },
  });
}

// Handles `invoice.payment_failed`. Stripe fires this once per failed
// collection attempt, so a single invoice can generate several of these
// over its retry schedule — each attempt is a real, distinct event worth
// keeping (not something to collapse into one row), which is why this
// writes a new FailedPayment per attempt rather than upserting by invoice.
// The webhook route's StripeEvent guard is what stops a *redelivery* of the
// same attempt from being recorded twice; this function doesn't need its
// own dedupe on top of that.
export async function syncStripeFailedPayment(stripeInvoice: Stripe.Invoice) {
  const customerId =
    typeof stripeInvoice.customer === "string"
      ? stripeInvoice.customer
      : stripeInvoice.customer?.id;

  const contact = customerId
    ? await findOrCreateContactForStripeCustomer({
        customerId,
        email: stripeInvoice.customer_email ?? null,
        name: stripeInvoice.customer_name ?? null,
      })
    : null;

  const amount = stripeInvoice.amount_due / 100;
  const reason = stripeInvoice.last_finalization_error?.message ?? null;
  // Invoices don't carry a stable charge ID on every API version, and one
  // invoice can fail multiple times — attempt_count makes each attempt's
  // synthetic ID unique so retried deliveries of the *same* attempt still
  // dedupe against the unique index, while a genuinely new attempt gets its
  // own row.
  const attemptKey = `${stripeInvoice.id}:attempt${stripeInvoice.attempt_count}`;

  await prisma.failedPayment.upsert({
    where: { stripeChargeId: attemptKey },
    update: {},
    create: {
      stripeChargeId: attemptKey,
      stripeInvoiceId: stripeInvoice.id,
      amount,
      reason,
      contactId: contact?.id ?? null,
    },
  });
}

function subscriptionBillingType(subscription: Stripe.Subscription): "MONTHLY" | "ONE_TIME" {
  const interval = subscription.items.data[0]?.price?.recurring?.interval;
  return interval === "month" ? "MONTHLY" : "ONE_TIME";
}

function subscriptionName(subscription: Stripe.Subscription): string {
  const price = subscription.items.data[0]?.price;
  if (price?.nickname) return price.nickname;
  if (typeof price?.product === "string") return `Stripe subscription (${price.product})`;
  return "Stripe subscription";
}

// Handles `customer.subscription.created`, `.updated`, and `.deleted`.
// Upserts by stripeSubscriptionId so the same Service row is kept in sync
// across the whole lifecycle rather than creating a new one on every event.
// Canceled subscriptions are soft-ended (endedAt set) rather than deleted,
// so past months still count correctly toward historical MRR.
export async function syncStripeSubscription(subscription: Stripe.Subscription) {
  const customerId =
    typeof subscription.customer === "string" ? subscription.customer : subscription.customer?.id;
  if (!customerId) return;

  const contact = await findOrCreateContactForStripeCustomer({
    customerId,
    email: null,
    name: null,
  });

  const isActive = subscription.status === "active" || subscription.status === "trialing";
  const endedAt = !isActive
    ? new Date((subscription.canceled_at ?? subscription.ended_at ?? Math.floor(Date.now() / 1000)) * 1000)
    : null;
  const amount = (subscription.items.data[0]?.price?.unit_amount ?? 0) / 100;
  const billingType = subscriptionBillingType(subscription);

  // Fetch the prior state *before* upserting so the MRR movement (new /
  // expansion / contraction / churn) can be classified by comparing old vs
  // new — Service only ever stores the *current* amount, so this is the
  // only place that transition is ever visible. Once overwritten by the
  // upsert below it's gone, which is exactly why ServiceMrrEvent exists as
  // an append-only log instead of being derived after the fact.
  const existing = await prisma.service.findUnique({ where: { stripeSubscriptionId: subscription.id } });

  const service = await prisma.service.upsert({
    where: { stripeSubscriptionId: subscription.id },
    update: {
      name: subscriptionName(subscription),
      billingType,
      amount,
      endedAt,
    },
    create: {
      stripeSubscriptionId: subscription.id,
      contactId: contact.id,
      name: subscriptionName(subscription),
      billingType,
      amount,
      endedAt,
    },
  });

  // MRR movement only applies to monthly recurring services — a one-time
  // Stripe subscription (e.g. an annual/non-monthly interval, classified
  // ONE_TIME by subscriptionBillingType) isn't part of MRR in the first
  // place, so it shouldn't generate NEW/EXPANSION/CONTRACTION/CHURN events.
  if (billingType !== "MONTHLY") return;

  let eventType: "NEW" | "EXPANSION" | "CONTRACTION" | "CHURN" | null = null;
  let amountDelta = 0;

  if (!existing) {
    if (isActive) {
      eventType = "NEW";
      amountDelta = amount;
    }
  } else {
    const wasActive = existing.endedAt === null;
    const previousAmount = existing.amount ?? 0;
    if (wasActive && !isActive) {
      eventType = "CHURN";
      amountDelta = -previousAmount;
    } else if (!wasActive && isActive) {
      // Reactivating a previously-canceled subscription is new MRR again,
      // not an "expansion" of MRR that was already zero.
      eventType = "NEW";
      amountDelta = amount;
    } else if (wasActive && isActive && amount !== previousAmount) {
      eventType = amount > previousAmount ? "EXPANSION" : "CONTRACTION";
      amountDelta = amount - previousAmount;
    }
    // wasActive && !isActive handled above; !wasActive && !isActive is a
    // no-op (still-canceled subscription updating unrelated fields).
  }

  if (eventType && amountDelta !== 0) {
    await prisma.serviceMrrEvent.create({
      data: { serviceId: service.id, type: eventType, amountDelta },
    });
  }
}
